---
# tasks file for mssql

- name: "Set MS SQL service name"
  set_fact:
    mssql_service_name: "{{ mssql_instance }}"
  when: mssql_instance == 'MSSQLSERVER'

- name: "Set MS SQL service name"
  set_fact:
    mssql_service_name: "MSSQL${{ mssql_instance }}"
  when: mssql_instance != 'MSSQLSERVER'

- name: "Check MS SQL service"
  win_service:
    name: "{{ mssql_service_name }}"
  register: mssql_service

- include_tasks: install.yml
  when: not mssql_service.exists

- name: "Configure MS SQL firewall"
  win_firewall_rule:
    name: MS SQL
    localport: "{{ mssql_port }}"
    action: allow
    direction: in
    protocol: tcp
    state: present
    enabled: True
  when:
    - mssql_tcp_enabled == 1
    - mssql_firewall
